### ISSUE TITLE
程序会偶发 CfxRemotingException  

### ISSUE THREAD

**Issue by yuanmingliang** [NetDimension/NanUI#102]
BUG描述 / Describe the bug
使用回调函数的时候，会偶发报错

系统环境 / Desktop :

OS: Windowx 10
Version   0.6.3239.4

【出现时间】：2020/4/17 星期五 下午 2:40:24
【异常类型】：CfxRemotingException
【异常信息】：Remote connection lost.
【堆栈调用】：
   at Chromium.Remote.RemoteCall.RequestExecution(RemoteConnection connection)
   at Chromium.Remote.CfrTaskRunner.PostTask(CfrTask task)
   at WeChatTool.Scripts.CallBack.FunctionCallBack.<CallBackAsync>d__0.MoveNext()

****************************异常文本****************************
【出现时间】：2020/4/17 星期五 下午 2:40:24
【异常类型】：CfxException
【异常信息】：The calling thread is not currently in this remote call context
【堆栈调用】：
   at Chromium.CfxRemoteCallContext.Exit()
   at Chromium.WebBrowser.BrowserCore.<>c__DisplayClass121_0.<RenderThreadInvoke>b__0()
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()

**Comment by XuanchenLin** [comment]
此问题已知晓，ChromiumFX的进程通信还是会存在一些不稳定的因素，后续版本还是决定使用CefGlue来作为NanUI的核心。希望在NanUI正式版来临前把核心确定下来。
